hcal_options = {
    'entireback': 'Entire Back',
    "funnel6": '6 Full-Width Modules then Prototype',
    "funnel5": '5 Full-Width Modules then Prototype',
    "funnel4": '4 Full-Width Modules then Prototype',
    "funnel3": '3 Full-Width Modules then Prototype',
    "funnel2": '2 Full-Width Modules then Prototype',
    "funnel1": '1 Full-Width Modules then Prototype',
    "funnel6_withside6": 'Thin Side, 6 Full-Width Modules then Prototype',
    "funnel5_withside6": 'Thin Side, 5 Full-Width Modules then Prototype',
    "funnel4_withside6": 'Thin Side, 4 Full-Width Modules then Prototype',
    "funnel3_withside6": 'Thin Side, 3 Full-Width Modules then Prototype',
    "funnel2_withside6": 'Thin Side, 2 Full-Width Modules then Prototype',
    "funnel1_withside6": 'Thin Side, 1 Full-Width Modules then Prototype',
    "narrowfunnel6": '6 Narrow Modules then Prototype',
    "narrowfunnel5": '5 Narrow Modules then Prototype',
    "narrowfunnel4": '4 Narrow Modules then Prototype',
    "narrowfunnel3": '3 Narrow Modules then Prototype',
    "narrowfunnel2": '2 Narrow Modules then Prototype',
    "narrowfunnel1": '1 Narrow Modules then Prototype',
    "narrowfunnel6_withside6": 'Thin Side, 6 Narrow Modules then Prototype',
    "narrowfunnel5_withside6": 'Thin Side, 5 Narrow Modules then Prototype',
    "narrowfunnel4_withside6": 'Thin Side, 4 Narrow Modules then Prototype',
    "narrowfunnel3_withside6": 'Thin Side, 3 Narrow Modules then Prototype',
    "narrowfunnel2_withside6": 'Thin Side, 2 Narrow Modules then Prototype',
    "narrowfunnel1_withside6": 'Thin Side, 1 Narrow Modules then Prototype',
    'prototype' : 'CERN 2022 Prototype',
    #'sixonly': 'Only 6 Modules',
    #'megaphone': 'Prototype then 6 Modules',
    'narrowback': '12 Narrow Modules',
}
